# Generated by Django 3.2.5 on 2021-08-12 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CV',
        ),
    ]
