# Generated by Django 3.2.5 on 2021-07-16 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='job',
            field=models.CharField(max_length=50),
        ),
    ]
