# Generated by Django 3.2.5 on 2021-08-12 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('community', '0002_delete_cv'),
    ]

    operations = [
        migrations.CreateModel(
            name='CV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.CharField(choices=[('j_ch1', '경영 사무'), ('j_ch2', '마케팅,광고,홍보'), ('j_ch3', 'IT,인터넷'), ('j_ch4', '디자인'), ('j_ch5', '무역,유통'), ('j_ch6', '영업,고객상담'), ('j_ch7', '서비스'), ('j_ch8', '연구개발,설계'), ('j_ch9', '생산,제조'), ('j_ch10', '교육'), ('j_ch11', '건설'), ('j_ch12', '의료'), ('j_ch13', '미디어'), ('j_ch14', '전문,특수직')], default='직무 선택', max_length=15, verbose_name='')),
                ('letter', models.TextField(verbose_name='')),
            ],
        ),
    ]
