# Generated by Django 3.2.5 on 2021-07-17 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_alter_post_job'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='CV',
        ),
    ]
